LLVM: llvm::PhiValues Class Reference
llvm::PhiValues Class Reference
Class for calculating and caching the underlying values of phis in a function.
#include "llvm/Analysis/PhiValues.h"
Public Types
using ValueSet = SmallSetVector< Value *, 4 >
Public Member Functions
PhiValues (const Function &F)
Construct an empty PhiValues.
const ValueSet & getValuesForPhi (const PHINode *PN)
Get the underlying values of a phi.
void invalidateValue (const Value *V)
Notify PhiValues that the cached information using V is no longer valid.
void releaseMemory ()
Free the memory used by this class.
void print (raw_ostream &OS) const
Print out the values currently in the cache.
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Handle invalidation events in the new pass manager.
Detailed Description
Class for calculating and caching the underlying values of phis in a function.
Initially the PhiValues is empty, and gets incrementally populated whenever it is queried.
Definition at line 40 of file PhiValues.h.
Member Typedef Documentation
ValueSet
using llvm::PhiValues::ValueSet = SmallSetVector<Value *, 4>
Definition at line 42 of file PhiValues.h.
Constructor & Destructor Documentation
PhiValues()
llvm::PhiValues::PhiValues (const Function & F) inline
Construct an empty PhiValues.
Definition at line 45 of file PhiValues.h.
References F.
Member Function Documentation
getValuesForPhi()
const PhiValues::ValueSet & PhiValues::getValuesForPhi (const PHINode * PN)
Get the underlying values of a phi.
This returns the cached value if PN has previously been processed, otherwise it processes it first.
Definition at line 125 of file PhiValues.cpp.
References assert().
Referenced by llvm::PhiValuesPrinterPass::run().
invalidate()
bool PhiValues::invalidate (Function & , const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator &)
Handle invalidation events in the new pass manager.
Definition at line 26 of file PhiValues.cpp.
References llvm::PreservedAnalyses::getChecker().
invalidateValue()
void PhiValues::invalidateValue (const Value * V)
Notify PhiValues that the cached information using V is no longer valid.
Whenever a phi has its operands modified the cached values for that phi (and the phis that use that phi) become invalid. A user of PhiValues has to notify it of this by calling invalidateValue on either the operand or the phi, which will then clear the relevant cached information.
Definition at line 137 of file PhiValues.cpp.
References N, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
print()
void PhiValues::print (raw_ostream & OS) const
Print out the values currently in the cache.
Definition at line 163 of file PhiValues.cpp.
References I, N, and OS.
Referenced by llvm::PhiValuesPrinterPass::run().
releaseMemory()
void PhiValues::releaseMemory ()
Free the memory used by this class.
Definition at line 157 of file PhiValues.cpp.
The documentation for this class was generated from the following files:
include/llvm/Analysis/PhiValues.h
lib/Analysis/PhiValues.cpp